import type { ScenarioRecord } from "@/lib/scenarios/types";

/** Minimal preset scenario fixture for frontend tests. */
export const marianaScenarioFixture: ScenarioRecord = {
  id: "preset-mariana",
  slug: "mariana",
  clientName: "Mariana Escobedo",
  clientTitle: "Directora de Operaciones",
  companyContext: "Clínica de Citas",
  difficultyLabel: "Media",
  indicator: "Visitas al local",
  painPoints: ["Medición", "ROI", "KPI"],
  industry: null,
  productSold: null,
  temperament: null,
  clientProblem: null,
  objections: [],
  winCriteria: null,
  language: "es",
  isPreset: true,
  config: {
    industry: "clinica",
    productSold: "software",
    clientProblem: "medición",
    objections: [],
    winCriteria: "cita",
    temperament: "escéptica",
    rounds: [],
    criteria: [],
    globalPositiveCriteria: [],
    openingLines: ["Hola"],
  },
};

/** Custom scenario fixture for authoring/edit tests. */
/** Custom scenario published to Biblioteca (not a clinic preset). */
export const publishedMarianaLibraryFixture: ScenarioRecord = {
  ...marianaScenarioFixture,
  id: "custom-mariana-published",
  isPreset: false,
  industry: "desarrolladora",
  productSold: "vivienda media",
  temperament: "escéptica",
  clientProblem: "medición",
  libraryPublishedAt: "2026-09-01T12:00:00.000Z",
};

export const customGymScenarioFixture: ScenarioRecord = {
  id: "custom-gym",
  slug: "laura-gimnasio",
  clientName: "Laura Méndez",
  clientTitle: "Gerente",
  companyContext: "Cadena de gimnasios",
  difficultyLabel: "Media",
  indicator: "Retención",
  painPoints: ["baja retención"],
  industry: "gimnasio",
  productSold: "membresía anual",
  temperament: "Impaciente",
  clientProblem: "baja retención de socios",
  objections: ["Muy caro"],
  winCriteria: "Clase prueba el viernes a las 18",
  language: "es",
  isPreset: false,
  config: {
    industry: "gimnasio",
    productSold: "membresía anual",
    clientProblem: "baja retención de socios",
    objections: ["Muy caro"],
    winCriteria: "Clase prueba el viernes a las 18",
    temperament: "Impaciente",
    rounds: [],
    criteria: [],
    globalPositiveCriteria: [],
    openingLines: ["¿Quién habla?"],
    language: "es",
    callType: "discovery",
    dimensionGuides: {},
  },
};
